language: php
php:
    - 7.0
script: phpunit
services:
    - mysql
before_install:
    - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot
before_script:
    - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
    - composer install --no-interaction